stages:
  - build

build_windows:
  stage: build

  tags:
    - windows

  before_script:
    - pip install -r requirements.txt

  script:
    - pyinstaller --onefile --windowed app.py
    - powershell Compress-Archive dist\app.exe dist\SpartanGroupBuilder.zip

  artifacts:
    name: "SpartanGroupBuilder-$CI_COMMIT_SHORT_SHA"
    paths:
      - dist/SpartanGroupBuilder.zip
    expire_in: 30 days

  only:
    - main